on: push

jobs:
  build-and-push:
    name: Build, push, and deploy container:w
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: kciter/aws-ecr-action@v1
      with:
        access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        repo: charlottes-automation 
        region: eu-west-1 
        tags: latest,${{ github.sha }}
        dockerfile: Dockerfile
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1
