on: push

jobs:
  build-and-push:
    name: Build, push, and deploy container:w
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: kciter/aws-ecr-action@v1
      with:
        access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        repo: charlottes-automation 
        region: eu-west-1 
        tags: ${{ github.sha }}
        dockerfile: Dockerfile
    - uses: actions/checkout@v1
      id: render-web-container
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: automation-api 
        image: charlottes-automation:${{ github.sha }}
