on: push

jobs:
  build-and-push:
    name: Build and push to Docker hub 
    runs-on: macos-latest 
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: nkuik89/automation-api
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: latest,${{ github.sha }}
